export const actions = {
	FETCH_PRODUCTS: "FETCH_PRODUCTS",
	FETCH_CART: "FETCH_CART",
	UPDATE_CART_PRODUCTS: "UPDATE_CART_PRODUCTS",
	ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
	CART_CHECKOUT: "CART_CHECKOUT",
	GENERATE_DISCOUNT: "GENERATE_DISCOUNT",
	VALIDATE_DISCOUNT: "VALIDATE_DISCOUNT",
};
