export const actions = {
	FETCH_PRODUCTS: "FETCH_PRODUCTS",
	FETCH_CART: "FETCH_CART",
	FETCH_DISCOUNTS: "FETCH_DISCOUNTS",
	FETCH_ADMIN_STORE_DETAILS: "FETCH_ADMIN_STORE_DETAILS",
	ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
	CART_CHECKOUT: "CART_CHECKOUT",
	GENERATE_DISCOUNT: "GENERATE_DISCOUNT",
	VALIDATE_DISCOUNT: "VALIDATE_DISCOUNT",
};
